import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Provider, useDispatch, useSelector } from "react-redux";
import { legacy_createStore as createStore } from "redux";

const api = "/api/v1";
const store = createStore((state = { products: [], status: "" }, action) => action.type === "set" ? { ...state, ...action.payload } : state);
let root;
function DataStewardApp() {
  const dispatch = useDispatch(); const { products, status } = useSelector((state) => state);
  const [view, setView] = useState("pending");
  const [rejectingProduct, setRejectingProduct] = useState(null);
  const [reason, setReason] = useState("");
  const loadQueue = async () => { const response = await fetch(`${api}/products/review/pending`, { credentials: "include" }); const data = await response.json().catch(() => ({})); dispatch({ type: "set", payload: response.ok ? { products: data, status: data.length ? "" : "No pending submissions." } : { status: data.error || "Sign in as a Data Steward to review submissions." } }); };
  const loadHistory = async () => { setView("history"); const response = await fetch(`${api}/products/review/history`, { credentials: "include" }); const data = await response.json().catch(() => ({})); dispatch({ type: "set", payload: response.ok ? { products: data, status: data.length ? "" : "No historical submissions." } : { status: data.error || "Sign in as a Data Steward to review submissions." } }); };
  React.useEffect(() => { loadQueue().catch(() => dispatch({ type: "set", payload: { status: "The review queue is unavailable right now." } })); }, []);
  const decide = async (product, action, rejectionReason) => { const response = await fetch(`${api}/products/${product.id}/${action}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: rejectionReason ? JSON.stringify({ reason: rejectionReason }) : undefined }); const data = await response.json().catch(() => ({})); dispatch({ type: "set", payload: { status: response.ok ? `${product.name} was ${action}ed.` : data.error || "The decision could not be completed." } }); if (response.ok) { setRejectingProduct(null); setReason(""); loadQueue(); } };
  return <div className="shell"><Header /><main className="page"><p className="eyebrow">Data stewardship</p><h1>Review product submissions.</h1><p className="lead">Approve listings for customer visibility or return them with a clear reason.</p><div className="actions"><button onClick={() => { setView("pending"); loadQueue(); }}>Load review queue</button><button onClick={loadHistory}>View review history</button></div>{status && <p className="status" role="status">{status}</p>}{rejectingProduct && <form className="panel" onSubmit={(event) => { event.preventDefault(); decide(rejectingProduct, "reject", reason); }}><h2>Reject {rejectingProduct.name}</h2><label>Rejection reason<textarea required minLength="3" maxLength="500" value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="actions"><button type="submit">Confirm rejection</button><button type="button" onClick={() => { setRejectingProduct(null); setReason(""); }}>Cancel</button></div></form>}<section className="grid">{products.map((product) => <article className="card" key={product.id}><h2>{product.name}</h2><p>{product.producer} · {product.category}</p><p>{product.description}</p><p>Status: {product.status}{product.rejection_reason ? ` - ${product.rejection_reason}` : ""}</p>{view === "pending" && <div className="actions"><button onClick={() => decide(product, "approve")}>Approve</button><button onClick={() => { setRejectingProduct(product); setReason(""); }}>Reject</button></div>}</article>)}</section></main></div>;
}
function Header() { const roles = window.summitSession?.roles || []; return <header className="topbar"><a className="brand" href="/">Summit Food Marketplace</a><nav className="nav"><a href="/">Customer</a>{roles.includes("Supplier") && <a href="/supplier">Supplier</a>}{roles.includes("DataSteward") && <a href="/datasteward">Data Steward</a>}<span>Signed in as {window.summitSession?.username}</span></nav></header>; }
export function bootstrap() { return Promise.resolve(); } export function mount() { root = createRoot(document.getElementById("root")); root.render(<Provider store={store}><DataStewardApp /></Provider>); return Promise.resolve(); } export function unmount() { root?.unmount(); return Promise.resolve(); }