import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Provider, useDispatch, useSelector } from "react-redux";
import { legacy_createStore as createStore } from "redux";

const api = `${window.location.protocol}//${window.location.hostname}:8080/api/v1`;
const store = createStore((state = { products: [], status: "" }, action) => action.type === "set" ? { ...state, ...action.payload } : state);
let root;
function DataStewardApp() {
  const dispatch = useDispatch(); const { products, status } = useSelector((state) => state);
  const [view, setView] = useState("pending");
  const loadQueue = async () => { const response = await fetch(`${api}/products/review/pending`, { credentials: "include" }); const data = await response.json(); dispatch({ type: "set", payload: response.ok ? { products: data, status: data.length ? "" : "No pending submissions." } : { status: "Sign in as a Data Steward to review submissions." } }); };
  const loadHistory = async () => { setView("history"); const response = await fetch(`${api}/products/review/history`, { credentials: "include" }); const data = await response.json(); dispatch({ type: "set", payload: response.ok ? { products: data, status: data.length ? "" : "No historical submissions." } : { status: "Sign in as a Data Steward to review submissions." } }); };
  const decide = async (product, action) => { const reason = action === "reject" ? window.prompt("Rejection reason (at least 3 characters):") : null; if (action === "reject" && !reason) return; const response = await fetch(`${api}/products/${product.id}/${action}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: reason ? JSON.stringify({ reason }) : undefined }); const data = await response.json(); dispatch({ type: "set", payload: { status: response.ok ? `${product.name} was ${action}ed.` : data.error || "The decision could not be completed." } }); if (response.ok) loadQueue(); };
  return <div className="shell"><Header /><main className="page"><p className="eyebrow">Data stewardship</p><h1>Review product submissions.</h1><p className="lead">Approve listings for customer visibility or return them with a clear reason.</p><div className="actions"><button onClick={() => { setView("pending"); loadQueue(); }}>Load review queue</button><button onClick={loadHistory}>View review history</button></div>{status && <p className="status">{status}</p>}<section className="grid">{products.map((product) => <article className="card" key={product.id}><h2>{product.name}</h2><p>{product.producer} · {product.category}</p><p>{product.description}</p><p>Status: {product.status}{product.rejection_reason ? ` - ${product.rejection_reason}` : ""}</p>{view === "pending" && <div className="actions"><button onClick={() => decide(product, "approve")}>Approve</button><button onClick={() => decide(product, "reject")}>Reject</button></div>}</article>)}</section></main></div>;
}
function Header() { const roles = window.summitSession?.roles || []; return <header className="topbar"><a className="brand" href="/">Summit Food Marketplace</a><nav className="nav"><a href="/">Customer</a>{roles.includes("Supplier") && <a href="/supplier">Supplier</a>}{roles.includes("DataSteward") && <a href="/datasteward">Data Steward</a>}<span>Signed in as {window.summitSession?.username}</span></nav></header>; }
export function bootstrap() { return Promise.resolve(); } export function mount() { root = createRoot(document.getElementById("root")); root.render(<Provider store={store}><DataStewardApp /></Provider>); return Promise.resolve(); } export function unmount() { root?.unmount(); return Promise.resolve(); }