sonar.projectKey=summit-food-marketplace
sonar.projectName=Summit Food Marketplace
sonar.sources=bff,backend,frontend/site
sonar.tests=backend/product-service/tests,backend/cart-service/tests,backend/user-service/tests
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/alembic/**
sonar.python.version=3.12