sonar.projectKey=summit-food-marketplace
sonar.projectName=Summit Food Marketplace
sonar.sources=bff,backend,frontend/src,frontend/customer-app/src,frontend/supplier-app/src,frontend/datasteward-app/src
sonar.tests=backend/product-service/tests,backend/cart-service/tests,backend/user-service/tests,frontend/cypress
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/alembic/**
sonar.python.version=3.12