import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Provider, useDispatch, useSelector } from "react-redux";
import { legacy_createStore as createStore } from "redux";

const api = `${window.location.protocol}//${window.location.hostname}:8080/api/v1`;
const store = createStore((state = { status: "", products: [] }, action) => action.type === "set" ? { ...state, ...action.payload } : state);
let root;
function SupplierApp() {
  const dispatch = useDispatch(); const { status, products } = useSelector((state) => state);
  const [form, setForm] = useState({ name: "", category: "", price: "", stock: "", producer: "", description: "" }); const [editingId, setEditingId] = useState(null);
  const loadMine = async () => { const response = await fetch(`${api}/products/mine`, { credentials: "include" }); const data = await response.json(); dispatch({ type: "set", payload: response.ok ? { products: data, status: "" } : { status: "Sign in as a Supplier to manage products." } }); };
  const submit = async (event) => { event.preventDefault(); const response = await fetch(`${api}/products${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, price: Number(form.price), stock: Number(form.stock) }) }); const data = await response.json(); if (response.ok) { setForm({ name: "", category: "", price: "", stock: "", producer: "", description: "" }); setEditingId(null); await loadMine(); } dispatch({ type: "set", payload: { status: response.ok ? `${data.name} was ${editingId ? "updated and resubmitted" : "submitted"} for review.` : data.error || "Product could not be saved." } }); };
  const edit = (product) => { setEditingId(product.id); setForm({ name: product.name, category: product.category, price: product.price, stock: product.stock, producer: product.producer, description: product.description }); };
  const deactivate = async (product) => { const response = await fetch(`${api}/products/${product.id}`, { method: "DELETE", credentials: "include" }); dispatch({ type: "set", payload: { status: response.ok ? `${product.name} was deactivated.` : "Product could not be deactivated." } }); if (response.ok) loadMine(); };
  return <div className="shell"><Header /><main className="page"><p className="eyebrow">Supplier workspace</p><h1>Submit and manage products.</h1><p className="lead">New and edited listings remain pending until a Data Steward approves them.</p><form className="panel" onSubmit={submit}><div className="actions">{Object.entries(form).map(([field, value]) => <label key={field}>{field[0].toUpperCase() + field.slice(1)}{field === "description" ? <textarea required minLength="10" value={value} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /> : <input required type={field === "price" || field === "stock" ? "number" : "text"} min={field === "price" ? "0.01" : field === "stock" ? "0" : undefined} step={field === "price" ? "0.01" : undefined} value={value} onChange={(event) => setForm({ ...form, [field]: event.target.value })} />}</label>)}</div><button type="submit">{editingId ? "Save and resubmit" : "Submit for review"}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm({ name: "", category: "", price: "", stock: "", producer: "", description: "" }); }}>Cancel edit</button>}</form><p className={status ? "status" : ""}>{status}</p><button onClick={loadMine}>Load my products</button><section className="grid">{products.map((product) => <article className="card" key={product.id}><h2>{product.name}</h2><p>{product.status}{product.rejection_reason ? `: ${product.rejection_reason}` : ""}</p><p>{product.stock} in stock · ${Number(product.price).toFixed(2)}</p><button onClick={() => edit(product)}>Edit</button> <button onClick={() => deactivate(product)}>Deactivate</button></article>)}</section></main></div>;
}
function Header() { const roles = window.summitSession?.roles || []; return <header className="topbar"><a className="brand" href="/">Summit Food Marketplace</a><nav className="nav"><a href="/">Customer</a>{roles.includes("Supplier") && <a href="/supplier">Supplier</a>}{roles.includes("DataSteward") && <a href="/datasteward">Data Steward</a>}<span>Signed in as {window.summitSession?.username}</span></nav></header>; }
export function bootstrap() { return Promise.resolve(); } export function mount() { root = createRoot(document.getElementById("root")); root.render(<Provider store={store}><SupplierApp /></Provider>); return Promise.resolve(); } export function unmount() { root?.unmount(); return Promise.resolve(); }